### ISSUE TITLE
Filter metrics by path?

### ISSUE THREAD

**Issue by tomas** [kindmetrics/kindmetrics#38]
Hi, just found about Kindmetrics. Looks nice.

Any plans to allow filtering metrics by path? (eg click on /foo and view pageviews and referrers for that specific URL)

**Comment by confact** [comment]
Hi, welcome to Kindmetrics! Love to have you here.

I have been thinking about this but haven't added any issue for it, so good you did! I think this makes totally sense and should add it to the todo list.

I will use this issue with status how this goes and will close it when done :)

**Comment by confact** [comment]
Hi @tomas, welcome to Kindmetrics! Love to have you here.

I have been thinking about this but haven't added any issue for it, so good you did! I think this makes totally sense and should add it to the todo list.

I will use this issue with status how this goes and will close it when done :)

**Comment by confact** [comment]
@tomas I will most likely be done with this issue this weekend - If I don't get busy with family stuff :)

I will update you once it is out (most likely some hours after this is closed.

**Comment by confact** [comment]
@tomas this have been out since yesterday. I am pushing some bugfixes for it right now.

Feel free to add a new issue for anything missing or not working as you thought.

**Comment by tomas** [comment]
Great! Thanks
