### ISSUE TITLE
Official Docker image at Docker Hub

### ISSUE THREAD

**Issue by alexanderadam** [kindmetrics/kindmetrics#40]
Hi Håkan,

I saw that you even created a [`Dockerfile`](https://github.com/kindmetrics/kindmetrics/blob/master/Dockerfile) but I can't find it at [Docker Hub](https://hub.docker.com/search?q=kindmetrics&type=image).

Maybe it would make sense to build releases automatically with GitHub Actions?

**PS:** Kindmetrics looks awesome so far!

**Comment by confact** [comment]
Hi, and thank you for your issue! Love to see some other people posting here now :)

I have a private docker container with sslcerts and stuff for my production.
But of course, I should put some docker up with some readme when I have time!

I will update the status on this here so you can follow :)

**Comment by alexanderadam** [comment]
You should be able to have your certificats outside of the application (i.e. by using Traefik or Caddy).

**Comment by confact** [comment]
@alexanderadam yea, I just haven't had time to do that. I use Kubernetes and it should be easy to add the certificate to the secrets there. It is on me really :)

I will try to do that soon so we can have a public docker up and running :)

**Comment by confact** [comment]
@alexanderadam a container is up and running on https://hub.docker.com/r/kindmetrics/kindmetrics - readme for environment variables need to be added but the hard part is fixed.

It will be publishing a new version on every push to master.

I consider this as done so will close it. Hope you like it @alexanderadam :)

**Comment by alexanderadam** [comment]
Awesome! Could you maybe add the readme for supported ENV variables etc?

**Comment by confact** [comment]
just added it @alexanderadam - Be aware that some stuff might brake as I looked at the code and saw some hardcoded stuff pointing at kindmetrics.io - I will try to move those to env variables as well.
