### ISSUE TITLE
Clickhouse support

### ISSUE THREAD

**Issue by alexanderadam** [kindmetrics/kindmetrics#42]
I saw that [you are using Postgres for now](https://github.com/kindmetrics/kindmetrics/blob/f0e2c006b3114a3f073f205e96708205f36d0ea8/config/database.cr#L7). I thought that it might be of interest for you that Yandex created a database exactly for analytics data for their service Yandex.Metrica. It is called [ClickHouse](https://github.com/ClickHouse/ClickHouse) and uses Apache 2.0 license.

It is probably easy to integrate something like this in the beginning, otherwise it might be difficult at a later point (i.e. like [it happened for Countly](https://github.com/Countly/countly-server/issues/1355)).

There are also a few crystal shards already: [clickhouse.cr](https://github.com/maiha/clickhouse.cr), [clickhouse-table](https://github.com/maiha/clickhouse-table) and [clickhouse-crystal](https://github.com/MeasureChina/clickhouse-crystal).

**Comment by confact** [comment]
thanks, @alexanderadam - I have thought of this as well but haven't added any issue for it.

It will be Clickhouse or something similar. At least something to speed up the event queries. :)

**Comment by confact** [comment]
This is now out.

Closing this.
