### ISSUE TITLE
Question: `timedout` vs `timed_out`?

### ISSUE THREAD

**Issue by alexanderadam** [kindmetrics/kindmetrics#60]
I'm just curious: any reason why [the method is `timedout`](https://github.com/kindmetrics/kindmetrics/blob/45d59382272a0ab03a75d3edae6753eed178f246/src/services/time_worker.cr#L14) instead of `timed_out`? :thinking: 

Same goes for `timespent` vs `time_spent`

**Comment by confact** [comment]
@alexanderadam nice catch! I am recoding it a bit for support for clickhouse in #59 actually. I will fix better support for classes with clickhouse first, then I can clean up this type of method names I haven't even think second thought on.

I think they should even be called `session_time_check` or similar - Like what it actually is doing.

Thanks again for the look through! :D

**Comment by alexanderadam** [comment]
> I think they should even be called `session_time_check` or similar - Like what it actually is doing.

I thought the same but I didn't wanted to go to get down to the nitty-gritty here. :wink: 

By the way: it's wonderful work, that you're doing! :+1:

**Comment by confact** [comment]
@alexanderadam Thank you! Love that you like it!

This has been fixed when I merged clickhouse in #59.
So I will close this. Feel free to give me feedback and create more issues :)
