### ISSUE TITLE
I'm not counted as `current active user` although I disabled all extensions for kindmetrics.io

### ISSUE THREAD

**Issue by alexanderadam** [kindmetrics/kindmetrics#61]
I refreshed a few times but I didn't got anything.

**EDIT:** Ah, I might have forgotten about the `DNT` setting! I guess that was the reason then?

Will `DNT` lead to a request in general?
I'm not sure how compliant this is but would it make sense to have a _minimal_ request that counts non-tracked requests? Like an API call that just increases a number?

**Comment by confact** [comment]
@alexanderadam My idea was to force DNT as much as not even sending a request at all when it is enabled.

When you have it on you know you don't want to be tracked and any request sent by then might give some mistrust.
That's why it is not sent.

I can reconsider adding some settings for enable it without any data if it is what people want.

**Comment by alexanderadam** [comment]
Ah, good to know.
Nah, personally I'm fine if no request is send at all. We still can reopen this issue if someone else wants to have it differently.

**Comment by alexanderadam** [comment]
Hi @confact,

I just saw [how fanthom is doing this](https://usefathom.com/support/tracking-advanced#:~:text=Honoring%20Do%20Not%20Track%20(DNT)) and maybe it's a good idea?

> By default we track every visitor to your website, regardless of them having DNT turned on or not. That’s because Fathom is privacy-focused analytics, so nothing personal or identifiable is ever “tracked”.
> 
> That said, if you would like to honor DNT then update your code to include `honor-dnt="true"`:
> 
> ```
> <script src="https://cdn.usefathom.com/script.js" site="ABCDEFG" honor-dnt="true" defer></script>
> ```

Also their other configuration options sound useful.

Either way: the kindmetrics should probably clarify this in [the FAQ](https://kindmetrics.io/#faq)
