### ISSUE TITLE
track language preferences

### ISSUE THREAD

**Issue by alexanderadam** [kindmetrics/kindmetrics#68]
Browsers also store and send language preferences and I guess it would make sense to track & show this as well.

This is how it looks in [Ackee](https://github.com/electerious/Ackee):
![Screenshot_20200702_115006](https://user-images.githubusercontent.com/372620/86344204-480b4c80-bc5a-11ea-915f-6dbc22145c84.png)

**Comment by confact** [comment]
@alexanderadam I thought that only the country is needed but, when reading your issue, I thought that this could be good to see what people have for language instead of what location. Good for locales, changes of content, and all that.

I might put this on the todo.

**Comment by alexanderadam** [comment]
> I thought that this could be good to see what people have for language instead of what location

Not _instead_ but additionally to that. Both things are different types of information. There are countries with different languages, too. People from Canada might have English or French as major preference. People from Switzerland might have French, German or Italian.

So it obviously makes a difference what info you need.

**Comment by confact** [comment]
@alexanderadam, of course, Didn't mean to remove countries, but some people might want languages more than countries for different things.

It could be added as part of the countries page. Planning to show a list of countries there like on the dashboard. I can add languages as part of that.
