### ISSUE TITLE
Onboarding wizard

### ISSUE THREAD

**Issue by alexanderadam** [kindmetrics/kindmetrics#78]
See also [the discussion](https://github.com/PostHog/posthog/pull/1051) and gif from PostHog:
![85067793-484a1900-b17f-11ea-9f33-97b4e192d903](https://user-images.githubusercontent.com/372620/87133094-1f590780-c297-11ea-985a-b0787d8e4f72.gif)

There're also various libraries for onboarding functionality.

**Comment by confact** [comment]
@alexanderadam I already have an onboarding. it consists of these steps:
1. signup
2. add domain
3. page for adding javascript, pinging for pageviews every 10 seconds
4. reload the page to the domain dashboard when pageviews found.

It doesn't have a step for picking the library as I don't have any libraries other than javascript for now.
Is the last thing you were thinking about, to have custom step 3 based on library you pick?

**Comment by alexanderadam** [comment]
Ah, sorry. We're good! My fault: I missed this!
