### ISSUE TITLE
Current demo shows pageviews for current day twice

### ISSUE THREAD

**Issue by alexanderadam** [kindmetrics/kindmetrics#91]
![27 August — Pageviews: 21](https://user-images.githubusercontent.com/372620/91536506-15f23000-e915-11ea-8c05-2ffdfeb7f529.png)

**Comment by alexanderadam** [comment]
Should the bugfix be already deployed (the issue still is present on the current instance at `app.kindmetrics.io`?

**Comment by confact** [comment]
@alexanderadam I am preparing this release as it is the full version. Still preparing the changes on the landing page as I am moving its hosting to the EU instead of GitHub pages. That and some small fixes on the pricing plan and such :)
