### ISSUE TITLE
Countries map doesn't fill the parent element

### ISSUE THREAD

**Issue by alexanderadam** [kindmetrics/kindmetrics#94]
This is how it looks like in current Firefox:
![](https://user-images.githubusercontent.com/372620/92630834-bad71a80-f2d0-11ea-95bb-4e6bb4a8f1ca.png)

**Comment by confact** [comment]
Nice catch @alexanderadam - seems to be connected to resize.

Fixed hopefully it in a commit and will be deployed soon :)
